//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMapperDefinition) DeepCopyInto(out *AutoMapperDefinition) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMapperDefinition.
func (in *AutoMapperDefinition) DeepCopy() *AutoMapperDefinition {
	if in == nil {
		return nil
	}
	out := new(AutoMapperDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoMapperDefinition) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMapperDefinitionGVK) DeepCopyInto(out *AutoMapperDefinitionGVK) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMapperDefinitionGVK.
func (in *AutoMapperDefinitionGVK) DeepCopy() *AutoMapperDefinitionGVK {
	if in == nil {
		return nil
	}
	out := new(AutoMapperDefinitionGVK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMapperDefinitionLabel) DeepCopyInto(out *AutoMapperDefinitionLabel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMapperDefinitionLabel.
func (in *AutoMapperDefinitionLabel) DeepCopy() *AutoMapperDefinitionLabel {
	if in == nil {
		return nil
	}
	out := new(AutoMapperDefinitionLabel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMapperDefinitionList) DeepCopyInto(out *AutoMapperDefinitionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AutoMapperDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMapperDefinitionList.
func (in *AutoMapperDefinitionList) DeepCopy() *AutoMapperDefinitionList {
	if in == nil {
		return nil
	}
	out := new(AutoMapperDefinitionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoMapperDefinitionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMapperDefinitionObject) DeepCopyInto(out *AutoMapperDefinitionObject) {
	*out = *in
	out.Source = in.Source
	out.Result = in.Result
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(AutoMapperDefinitionLabel)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.VarMap != nil {
		in, out := &in.VarMap, &out.VarMap
		*out = new([]AutoMapperVariableMap)
		if **in != nil {
			in, out := *in, *out
			*out = make([]AutoMapperVariableMap, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMapperDefinitionObject.
func (in *AutoMapperDefinitionObject) DeepCopy() *AutoMapperDefinitionObject {
	if in == nil {
		return nil
	}
	out := new(AutoMapperDefinitionObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMapperDefinitionSpec) DeepCopyInto(out *AutoMapperDefinitionSpec) {
	*out = *in
	if in.Relationships != nil {
		in, out := &in.Relationships, &out.Relationships
		*out = make([]AutoMapperDefinitionObject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMapperDefinitionSpec.
func (in *AutoMapperDefinitionSpec) DeepCopy() *AutoMapperDefinitionSpec {
	if in == nil {
		return nil
	}
	out := new(AutoMapperDefinitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMapperDefinitionStatus) DeepCopyInto(out *AutoMapperDefinitionStatus) {
	*out = *in
	if in.Relationships != nil {
		in, out := &in.Relationships, &out.Relationships
		*out = make([]AutoMapperRelLocator, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMapperDefinitionStatus.
func (in *AutoMapperDefinitionStatus) DeepCopy() *AutoMapperDefinitionStatus {
	if in == nil {
		return nil
	}
	out := new(AutoMapperDefinitionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMapperRelLocator) DeepCopyInto(out *AutoMapperRelLocator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMapperRelLocator.
func (in *AutoMapperRelLocator) DeepCopy() *AutoMapperRelLocator {
	if in == nil {
		return nil
	}
	out := new(AutoMapperRelLocator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMapperRelationship) DeepCopyInto(out *AutoMapperRelationship) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMapperRelationship.
func (in *AutoMapperRelationship) DeepCopy() *AutoMapperRelationship {
	if in == nil {
		return nil
	}
	out := new(AutoMapperRelationship)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoMapperRelationship) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMapperRelationshipList) DeepCopyInto(out *AutoMapperRelationshipList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AutoMapperRelationship, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMapperRelationshipList.
func (in *AutoMapperRelationshipList) DeepCopy() *AutoMapperRelationshipList {
	if in == nil {
		return nil
	}
	out := new(AutoMapperRelationshipList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoMapperRelationshipList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMapperRelationshipSpec) DeepCopyInto(out *AutoMapperRelationshipSpec) {
	*out = *in
	out.Source = in.Source
	out.Result = in.Result
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(AutoMapperDefinitionLabel)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.VarMap != nil {
		in, out := &in.VarMap, &out.VarMap
		*out = new([]AutoMapperVariableMap)
		if **in != nil {
			in, out := *in, *out
			*out = make([]AutoMapperVariableMap, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMapperRelationshipSpec.
func (in *AutoMapperRelationshipSpec) DeepCopy() *AutoMapperRelationshipSpec {
	if in == nil {
		return nil
	}
	out := new(AutoMapperRelationshipSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMapperRelationshipStatus) DeepCopyInto(out *AutoMapperRelationshipStatus) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]AutoMapperRelationshipStatusMappings, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMapperRelationshipStatus.
func (in *AutoMapperRelationshipStatus) DeepCopy() *AutoMapperRelationshipStatus {
	if in == nil {
		return nil
	}
	out := new(AutoMapperRelationshipStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMapperRelationshipStatusMappings) DeepCopyInto(out *AutoMapperRelationshipStatusMappings) {
	*out = *in
	out.Source = in.Source
	out.Result = in.Result
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMapperRelationshipStatusMappings.
func (in *AutoMapperRelationshipStatusMappings) DeepCopy() *AutoMapperRelationshipStatusMappings {
	if in == nil {
		return nil
	}
	out := new(AutoMapperRelationshipStatusMappings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMapperRelationshipStatusResource) DeepCopyInto(out *AutoMapperRelationshipStatusResource) {
	*out = *in
	out.GVK = in.GVK
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMapperRelationshipStatusResource.
func (in *AutoMapperRelationshipStatusResource) DeepCopy() *AutoMapperRelationshipStatusResource {
	if in == nil {
		return nil
	}
	out := new(AutoMapperRelationshipStatusResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMapperVariableMap) DeepCopyInto(out *AutoMapperVariableMap) {
	*out = *in
	in.SourceVar.DeepCopyInto(&out.SourceVar)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMapperVariableMap.
func (in *AutoMapperVariableMap) DeepCopy() *AutoMapperVariableMap {
	if in == nil {
		return nil
	}
	out := new(AutoMapperVariableMap)
	in.DeepCopyInto(out)
	return out
}
