//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMapperDefinition) DeepCopyInto(out *AutoMapperDefinition) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMapperDefinition.
func (in *AutoMapperDefinition) DeepCopy() *AutoMapperDefinition {
	if in == nil {
		return nil
	}
	out := new(AutoMapperDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoMapperDefinition) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMapperDefinitionGVK) DeepCopyInto(out *AutoMapperDefinitionGVK) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMapperDefinitionGVK.
func (in *AutoMapperDefinitionGVK) DeepCopy() *AutoMapperDefinitionGVK {
	if in == nil {
		return nil
	}
	out := new(AutoMapperDefinitionGVK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMapperDefinitionList) DeepCopyInto(out *AutoMapperDefinitionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AutoMapperDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMapperDefinitionList.
func (in *AutoMapperDefinitionList) DeepCopy() *AutoMapperDefinitionList {
	if in == nil {
		return nil
	}
	out := new(AutoMapperDefinitionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoMapperDefinitionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMapperDefinitionSpec) DeepCopyInto(out *AutoMapperDefinitionSpec) {
	*out = *in
	if in.Maps != nil {
		in, out := &in.Maps, &out.Maps
		*out = make([]AutoMapperObject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMapperDefinitionSpec.
func (in *AutoMapperDefinitionSpec) DeepCopy() *AutoMapperDefinitionSpec {
	if in == nil {
		return nil
	}
	out := new(AutoMapperDefinitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMapperDefinitionStatus) DeepCopyInto(out *AutoMapperDefinitionStatus) {
	*out = *in
	if in.MappedItems != nil {
		in, out := &in.MappedItems, &out.MappedItems
		*out = make(map[string]AutoMapperDefinitionStatusMapped, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMapperDefinitionStatus.
func (in *AutoMapperDefinitionStatus) DeepCopy() *AutoMapperDefinitionStatus {
	if in == nil {
		return nil
	}
	out := new(AutoMapperDefinitionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMapperDefinitionStatusMapped) DeepCopyInto(out *AutoMapperDefinitionStatusMapped) {
	*out = *in
	out.Source = in.Source
	out.Result = in.Result
	if in.BasisVars != nil {
		in, out := &in.BasisVars, &out.BasisVars
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.VarMap = in.VarMap
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make(map[string]AutoMapperDefinitionStatusResource, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMapperDefinitionStatusMapped.
func (in *AutoMapperDefinitionStatusMapped) DeepCopy() *AutoMapperDefinitionStatusMapped {
	if in == nil {
		return nil
	}
	out := new(AutoMapperDefinitionStatusMapped)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMapperDefinitionStatusResource) DeepCopyInto(out *AutoMapperDefinitionStatusResource) {
	*out = *in
	out.GVK = in.GVK
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMapperDefinitionStatusResource.
func (in *AutoMapperDefinitionStatusResource) DeepCopy() *AutoMapperDefinitionStatusResource {
	if in == nil {
		return nil
	}
	out := new(AutoMapperDefinitionStatusResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMapperObject) DeepCopyInto(out *AutoMapperObject) {
	*out = *in
	out.Source = in.Source
	out.Result = in.Result
	if in.LabelBasis != nil {
		in, out := &in.LabelBasis, &out.LabelBasis
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.NamespaceBasis != nil {
		in, out := &in.NamespaceBasis, &out.NamespaceBasis
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.VarMap != nil {
		in, out := &in.VarMap, &out.VarMap
		*out = new([]AutoMapperVariableMap)
		if **in != nil {
			in, out := *in, *out
			*out = make([]AutoMapperVariableMap, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMapperObject.
func (in *AutoMapperObject) DeepCopy() *AutoMapperObject {
	if in == nil {
		return nil
	}
	out := new(AutoMapperObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMapperVariableMap) DeepCopyInto(out *AutoMapperVariableMap) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMapperVariableMap.
func (in *AutoMapperVariableMap) DeepCopy() *AutoMapperVariableMap {
	if in == nil {
		return nil
	}
	out := new(AutoMapperVariableMap)
	in.DeepCopyInto(out)
	return out
}
