kind: Cluster
name: local
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane # single node for control plane + deployments for dev
kubeadmConfigPatchesJSON6902:
- group: kubeadm.k8s.io
  version: v1beta3
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServer/certSANs/-
      value: host.docker.internal