# permissions for end users to view automapperdefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: automapperdefinition-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: lazy
    app.kubernetes.io/part-of: lazy
    app.kubernetes.io/managed-by: kustomize
  name: automapperdefinition-viewer-role
rules:
- apiGroups:
  - tardelli.com.au
  resources:
  - automapperdefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tardelli.com.au
  resources:
  - automapperdefinitions/status
  verbs:
  - get
