---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - tardelli.com.au
  resources:
  - automapperdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tardelli.com.au
  resources:
  - automapperdefinitions/finalizers
  verbs:
  - update
- apiGroups:
  - tardelli.com.au
  resources:
  - automapperdefinitions/status
  verbs:
  - get
  - patch
  - update
