apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/DanielTardelli/lazyOperator.git'
    targetRevision: HEAD
    path: .k8
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: lazy
  syncPolicy:
    automated:
      prune: false
      selfHeal: false